---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1565lf99r9t4e7mf2rtmwepdtj0kk7ve2xppk0q45r7qz9km6me0srzxl70

  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1565lf99r9t4e7mf2rtmwepdtj0kk7ve2xppk0q45r7qz9km6me0srzxl70
