# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: kube-system
stringData:
    email: ENC[AES256_GCM,data:6pcMUaVGALi8AwbhX9uL/D2VlA==,iv:ttNDANRi65MkihujZY0sOv1DOy/7YQL5yLr/zNLFp/0=,tag:mXpBCKwoaEWUcqV8eO3u4g==,type:str]
    api-key: ENC[AES256_GCM,data:i5WiP20d23LHQ22o3wZBAHwBL5hMugcvgDLvXaL/r9gOptDMNg==,iv:/BvyvwkHxHvHshIE9BmoSmWCcb/mYXX6E+CpwMOo07U=,tag:OiTf917IFVIunKul3aJD1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1565lf99r9t4e7mf2rtmwepdtj0kk7ve2xppk0q45r7qz9km6me0srzxl70
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aUYzdGxyZHRJcnhLUHdn
            aXo5QWZ3eVc5N1dzSEs2em9QVEtHbitZcWxvCllZVDBwNW1sejZ1NVFMWW1VRnkr
            ZjJ3ZW1FNERFS21tdlFBd0duNEt6VmMKLS0tIFVhTFEzTDZuaEdacTZxS0l3NkxP
            UjFNUW1WZ3J1SkEzUWdZY1BacE5MaWsKQP24QPJWvleJ6zPmxH3zczyXY2gaUqsY
            W4YgFgK1cnvRE6Ok7jmBTHPt9mAqbHeF8zrxEz5JvabX3zJaVaIV7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-08T04:18:05Z"
    mac: ENC[AES256_GCM,data:1NQCOlKtnBOvVt4Uhn50PeB+f5mrgr2dDMS66+PGsrftsIi53EKGK2yYEj04UH5XF0LxALaL3zDYtXVRhYTv2jGJpjnTUzDiFoAAiTK8uhQ92M4bgNb5IpvW1DVzUIRNGbtNui8icLqvCrhVZlzJ6XxwiFAihm4BObGK8qFKmTc=,iv:vo/N4yUsiBD0rSA1uHAZilSnUb7LEAxXFNCq712vkPE=,tag:sCOqCgQAq50t1DK772nxGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
