---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/New_York
  # METALLB_LB_RANGE:
  # METALLB_K8S_GATEWAY_ADDR:
  # METALLB_INGRESS_ADDR:
