# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:Eqj6m9LPBlKE9jmw1JFHD1Wmgy4m7oQfmMe/3HEx9d95fHVWmA==,iv:+DTTv5+WAzLNyhdkfOsUEWlKnZka+AEMS6MpvEp5Xg8=,tag:6u0BxfGcDnIzO8S+qkzqMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1565lf99r9t4e7mf2rtmwepdtj0kk7ve2xppk0q45r7qz9km6me0srzxl70
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WXdPbVRPRUx6M3d2a3N5
            Z3Q3dE9hN3ZqMUFoOHNEa1diVDNPdXIxL3cwCmw2SzRKMDh2citPYjE4RHhvSUQz
            WGxOdXdGamlkVkl1YUFwNFN1d0V3ZDAKLS0tIHB6Mkh2QUJHOGFKM3F6L0Q1Slgw
            MlBMSzlTM0FBei9sS0RlY3pCNENzTEkKkuqb+4AMUHBmkfxylwxdtPUPI4ugBODe
            vYs8fHF9RJunV/Nl61aC86za4RIviT6rGnS703uOSDBs7nsNRNVjmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-08T04:03:37Z"
    mac: ENC[AES256_GCM,data:CowWda4/o5Ox2ZrzhH81NEEbrqpRc3kpOCKKzAUbivSRFiRG4DRtfx1+K3sW5FLzjhQRLcLc9yRp/zAGXmuCQdyiLnBqiPeXCqp1uL2eiK1Hy9V9UqDjrWAjIMOW9UqLWNKuX2mzAGwuArxKnTxWTO891ZnYXPtLalEcPhmgVOw=,iv:i+OOvufeYEauAbX1kYe+z1A9DK321ORZypgk8xN9CQQ=,tag:ozKBVC802akIBsg6qPpRhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
